#!/bin/sh -x
# vim: set foldmethod=marker :

ip route del default

# Disable kernel log on /dev/ttyO0. {{{
if [ -f /boot/uboot/uEnv.txt ] ; then
	sed -i -e 's/console=${console} //' /boot/uboot/uEnv.txt
elif [ -f /boot/uEnv.txt ] ; then
	if ! grep -q console /boot/uEnv.txt ; then
		echo 'console=ttyO2,115200n8' >> /boot/uEnv.txt
	fi
else
	echo >&2 'No uEnv.txt found!'
fi
# }}}

# Set up eth0. {{{
cat > /etc/network/interfaces <<EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# WiFi Example
#auto wlan0
#iface wlan0 inet dhcp
#    wpa-ssid "essid"
#    wpa-psk  "password"

# Ethernet/RNDIS gadget (g_ether)
# ... or on host side, usbnet and random hwaddr
# Note on some boards, usb0 is automaticly setup with an init script
allow-hotplug usb0
auto usb0
iface usb0 inet static
	address 192.168.7.2
	netmask 255.255.255.0

allow-hotplug eth0
auto eth0
iface eth0 inet static
	address 192.168.76.2
	netmask 255.255.255.0
EOF
# }}}

# Shut down. {{{
shutdown -h now
# }}}
