#!/bin/sh -x
#Set up masquerading.
REMOTE=`ip route | grep 'default via' | cut -f5 -d' '`
iptables --flush -t nat
iptables -t nat -A POSTROUTING -o $REMOTE -j MASQUERADE
echo 1 > /proc/sys/net/ipv4/ip_forward

if [ "`dpkg -l sshpass | tail -n 1 | cut -b-2`" != 'ii' ] ; then
	apt-get install sshpass
fi
if [ "`dpkg -l apt-cacher-ng | tail -n 1 | cut -b-2`" != 'ii' ] ; then
	apt-get install apt-cacher-ng
fi
