#!/bin/sh -x
# vim: set foldmethod=marker :

# Only run on beaglebone. {{{
if [ `dpkg --print-architecture` != armhf ] ; then
	echo >&2 "This script should not run on the host.  Run upload instead"
	exit 1
fi
# }}}

exec 2> /home/debian/setup-log
HOSTNAME="$1"
FAST="$2"
read DATE
date --set "$DATE"

DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND
# Set proxy for faster download.
http_proxy='http://192.168.7.1:3142'
export http_proxy

# Disable kernel log on /dev/ttyO0 for Black, enable cape-universal for Green. {{{
systemctl mask serial-getty@ttyO0.service
if [ -f /boot/uboot/uEnv.txt ] ; then
	sed -i -e 's/console=${console} //' /boot/uboot/uEnv.txt
elif [ -f /boot/uEnv.txt ] ; then
	sed -i -e 's/^cape_enable=.*$/cape_enable=capemgr.enable_partno=cape-universal,cape-univ-hdmi/' /boot/uEnv.txt
	if ! grep -q '^console=' /boot/uEnv.txt ; then
		echo 'console=ttyO2,115200n8' >> /boot/uEnv.txt
	fi
else
	echo >&2 'No uEnv.txt found!'
fi
# }}}

# Allow hotplug on usb. {{{
if ! grep -q '^auto usb0' /etc/network/interfaces ; then
	cat >>/etc/network/interfaces <<EOF
allow-hotplug usb0
auto usb0
EOF
fi
# }}}

# Set up eth0. {{{
sed -i -re 's/wired_interface = .*$/wired_interface = None/' /etc/wicd/manager-settings.conf
sed -i -re '/\s*(network|gateway)\s/d' /etc/network/interfaces
if ! grep -q '^iface eth0' /etc/network/interfaces ; then
	cat >>/etc/network/interfaces <<EOF

allow-hotplug eth0
auto eth0
iface eth0 inet static
	address 192.168.76.2
	netmask 255.255.255.0
EOF
fi
# }}}

# Set the default route through USB while this script is running. {{{
IP=`ip route | grep usb0 | grep / | cut -f1 -d/`
ip route replace default via ${IP%.*}.1
# }}}

# Set up nameserver. {{{
echo 'nameserver 8.8.8.8' > /etc/resolv.conf
# }}}q

# Allow printer user to use sudo. {{{
echo 'franklin3d ALL=NOPASSWD:ALL' > /etc/sudoers.d/franklin
# }}}

if [ "$FAST" = false ] ; then
# Remove junk. {{{
	rm -f /etc/init.d/led_aging.sh
	apt-get -y remove --purge modemmanager gnome udhcpd lightdm xserver-xorg lxde
	apt-get -y autoremove
# }}}

# Move files to their proper location. {{{
	cp /tmp/upgrade.gpg /root/
	cp -r /tmp/Repetier-Server /var/lib/
# }}}

# Set hostname. {{{
	if grep -q 'beaglebone' /etc/hosts ; then
		echo $HOSTNAME > /etc/hostname
		sed -i -e "s/^.*beaglebone.*$/127.0.1.1	$HOSTNAME/" /etc/hosts
	fi
# }}}

# Add Franklin's repository to sources.list. {{{
	cat > /etc/apt/sources.list.d/franklin.list <<EOF
deb http://wijnen.dtdns.net/archive sid/all/
deb http://wijnen.dtdns.net/archive sid/armhf/
EOF
# }}}

# Upgrade system. {{{
	sed -i -e 's/wheezy/jessie/g' /etc/apt/sources.list
	apt-get -y update
	yes | apt-get --force-yes -y upgrade
	apt-get clean
# }}}

# Disable webserver.
systemctl disable bonescript.socket
systemctl disable bonescript.service
systemctl stop bonescript.socket
systemctl stop bonescript.service

# Install new packages. {{{
	apt-get -y install --force-yes --allow-unauthenticated wijnen-archive-keyring
	apt-get -y update
	yes | apt-get -y install --force-yes python3 dnsmasq apache2 avrdude
	systemctl enable apache2.service
	dpkg -i /tmp/Repetier-Server-0.60.4-Linux.deb
	rm -f /etc/default/franklin
	yes | apt-get -y install --force-yes franklin
# }}}
fi

# Set up Franklin. {{{
cat > /etc/default/franklin <<EOF
AUTODETECT=False
TLS=False
EOF
# }}}

# Set up dnsmasq. {{{
if [ -f /etc/dnsmasq.conf ] ; then
	sed -i -e '/^dhcp-range=/d' /etc/dnsmasq.conf
	echo >> /etc/dnsmasq.conf
	echo 'dhcp-range=192.168.76.3,192.168.76.200,12h' >> /etc/dnsmasq.conf
	echo 'dhcp-range=192.168.7.1,192.168.7.1,10m' >> /etc/dnsmasq.conf
	if ! grep -q '^dhcp-option=3' /etc/dnsmasq.conf ; then
		echo 'dhcp-option=3' >> /etc/dnsmasq.conf
	fi
	if ! grep -q '^dhcp-option=6' /etc/dnsmasq.conf ; then
		echo 'dhcp-option=6' >> /etc/dnsmasq.conf
	fi
fi
# }}}

# Set up auto-upgrade from usb storage. {{{
cat > /etc/rc.local <<EOF
#!/bin/sh
config-pin P9_11 uart
config-pin P9_13 uart
sleep 10
if [ -b /dev/sda1 ] ; then
	if mount /dev/sda1 /mnt ; then
		for i in /mnt/*.sig ; do
			target="\${i%.sig}"
			if ! [ -f "\$i" ] ; then continue ; fi
			if ! [ -f "\$target" ] ; then continue ; fi
			if gpg --ignore-time-conflict --keyring /root/upgrade.gpg --no-default-keyring --verify "\$i" "\$target" ; then
				if [ "\${target%.deb}" != "\$target" ] ; then
					dpkg -i "\$target"
					yes | apt-get install -f
				else
					cp "\$target" /tmp/script
					chmod a+x /tmp/script
					/tmp/script
				fi
			fi
		done
		umount /mnt
	fi
fi
EOF
chmod a+x /etc/rc.local
# }}}

# Allow shutdown through web site. {{{
SUDOER=/etc/sudoers.d/athena-shutdown
echo 'www-data ALL=(root)NOPASSWD:/sbin/shutdown' > "$SUDOER"
chmod 0440 "$SUDOER"

cat > /usr/lib/cgi-bin/shutdown << EOF
#!/usr/bin/python3

import cgi
import os
import socket

f = cgi.FieldStorage()
hostname = socket.getfqdn()

if f.getfirst('halt'):
	os.system('sudo shutdown -h now')
	print('Content-Type: text/html;charset=utf8')
	print('')
	print('''\
<!DOCTYPE html>
<html>
	<head>
		<title>Shutting Down %s</title>
	</head>
	<body>
		<h1>Shutting Down %s</h1>
	</body>
</html>
''' % (hostname, hostname))
else:
	print('Content-Type: text/html;charset=utf8')
	print('')
	print('''\
<!DOCTYPE html>
<html>
	<head>
		<title>Shut Down %s?</title>
	</head>
	<body>
		<h1>Shut Down %s?</title>
		<form>
			<input type='hidden' name='halt' value='halt'/>
			<input type='submit' name='submit' value='Shut Down %s'/>
		</form>
	</body>
</html>
''' % (hostname, hostname, hostname))
EOF

chmod a+x /usr/lib/cgi-bin/shutdown
# }}}

# Set passwords. {{{
chpasswd <<EOF
root:reprap
debian:reprap
EOF
sed -i -e 's/^PermitRootLogin .*$/PermitRootLogin no/' /etc/ssh/sshd_config
# }}}

cat /etc/hostname

# Shut down. {{{
shutdown -h now
# }}}
